### ISSUE TITLE
Terminating app due to uncaught exception

### ISSUE THREAD

**Issue by asadali737** [lll1024/JVDrawingBoard#1]
As soon as your app lunches, simple click on anywhere on the view & app gets crashed. :(
Below is the details of crash logs.

2017-05-17 12:22:01.666 JVDrawingBoard[7511:423947] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSArrayM insertObject:atIndex:]: object cannot be nil'

`*** First throw call stack:
(
	0   CoreFoundation                      0x0000000110b74b0b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00000001105d9141 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000110aa94a3 -[__NSArrayM insertObject:atIndex:] + 1603
	3   JVDrawingBoard                      0x000000010fffb77e -[JVDrawingView touchesEnded:withEvent:] + 414
	4   UIKit                               0x000000011194e49a -[UIWindow _sendTouchesForEvent:] + 2707
	5   UIKit                               0x000000011194fbb0 -[UIWindow sendEvent:] + 4114
	6   UIKit                               0x00000001118fc7b0 -[UIApplication sendEvent:] + 352
	7   UIKit                               0x00000001120dfadc __dispatchPreprocessedEventFromEventQueue + 2926
	8   UIKit                               0x00000001120d7a3a __handleEventQueue + 1122
	9   CoreFoundation                      0x0000000110b1ac01 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	10  CoreFoundation                      0x0000000110b000cf __CFRunLoopDoSources0 + 527
	11  CoreFoundation                      0x0000000110aff5ff __CFRunLoopRun + 911
	12  CoreFoundation                      0x0000000110aff016 CFRunLoopRunSpecific + 406
	13  GraphicsServices                    0x0000000116161a24 GSEventRunModal + 62
	14  UIKit                               0x00000001118df0d4 UIApplicationMain + 159
	15  JVDrawingBoard                      0x000000010fffdc1f main + 111
	16  libdyld.dylib                       0x000000011432365d start + 1
	17  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException`

<img width="1086" alt="screenshot 2017-05-17 12 25 39" src="https://cloud.githubusercontent.com/assets/1748831/26142882/f573082e-3afb-11e7-8436-2cc251c90e45.png">

**Comment by lll1024** [comment]
@asadali737  The bug has been solved; thank u

**Comment by asadali737** [comment]
Yes it's fixed.
